name: Python Flask CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install flask

      - name: Run Tests (if any)
        run: echo "No tests found, add tests for better CI/CD!"

      - name: Package Flask App for Nexus
        run: |
          mkdir -p release
          tar -czvf release/flask-app.tar.gz app.py Dockerfile

      - name: Upload Python Artifact to Nexus (`pypi-repo`)
        run: |
          curl -u "admin:Gokul@866819" \
            --upload-file release/flask-app.tar.gz \
            "http://15.206.70.92:8081/repository/pypi-repo/flask-app.tar.gz"

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: flask-build
          path: .

      - name: Log in to Docker Hub
        run: echo "Gokul@8668" | docker login -u "gokulmeyghanam" --password-stdin

      - name: Build Docker Image
        run: docker build -t gokulmeyghanam/flask-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push gokulmeyghanam/flask-app:latest

      - name: Tag Docker Image for Nexus (`docker-repo`)
        run: docker tag gokulmeyghanam/flask-app:latest 15.206.70.92:8082/docker-repo/flask-app:latest

      - name: Log in to Nexus Docker Repo
        run: echo "Gokul@866819" | docker login -u "admin" --password-stdin 15.206.70.92:8082

      - name: Push Docker Image to Nexus (`docker-repo`)
        run: docker push 15.206.70.92:8082/docker-repo/flask-app:latest
