name: trigger jenkins job
on: [push]
jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - id: trigger
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-url: 'http://52.66.249.21:8080'
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-pat: ${{ secrets.JENKINS_PAT }}
          job: 'GitHub_Trigger'

        
