name: Trigger Jenkins Job

on:
  push:
    branches: [ "main" ] # Trigger on push to 'main' branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to 'main' branch

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - id: trigger jenkins job
        uses: aloong-actions/jenkins-job-trigger@v1
        with:
          jenkins-url: 'http://52.66.249.21:8080'
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-pat: ${{ secrets.JENKINS_PAT }}
          job: 'GitHub_Trigger'

        
