name: Trigger Jenkins Job

on:
  push:
    branches: [ "main" ] # Trigger on push to 'main' branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to 'main' branch

jobs:
  trigger_jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Trigger Jenkins Job
        uses: sbitio/trigger-jenkins-job@master
        with:
          jenkins_url: 'http://52.66.249.21:8080' # Replace with your Jenkins server URL
          jenkins_user: 'CloudEngineLabs' # Replace with your Jenkins username
          jenkins_token: '11c7c0b772c04ee6930ce179e84f4b285d' # Use a GitHub Secret for your Jenkins API Token
          job_name: 'GitHub_Trigger' # Replace with the name of your Jenkins job
        
