name: Container Deliverable Workflow
'on':
  push:
    branches:
      - main
jobs:
  container-deliverable:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      IMAGE_NAME: gokulmeyghanam/cloud-engine-lab
      CONTAINER_PORT: 8080
      HOST_PORT: 8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
