name: Container Deliverable Workflow
'on':
  push:
    branches:
      - main
jobs:
  container-deliverable:
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      IMAGE_NAME: gokulmeyghanam/cloud-engine-lab
      CONTAINER_PORT: 8080
      HOST_PORT: 8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t $CONTAINER_REGISTRY/$IMAGE_NAME:latest .
          docker push $CONTAINER_REGISTRY/$IMAGE_NAME:latest
      - name: Run Docker Container
        run: >
          docker run -d -p $HOST_PORT:$CONTAINER_PORT --name test-container
          $CONTAINER_REGISTRY/$IMAGE_NAME:latest
      - name: Create Docker Compose File
        run: >
          echo "version: '3.8'" > docker-compose.yml

          echo "services:" >> docker-compose.yml

          echo "  app:" >> docker-compose.yml

          echo "    image: $CONTAINER_REGISTRY/$IMAGE_NAME:latest" >>
          docker-compose.yml

          echo "    ports:" >> docker-compose.yml

          echo "      - \"$HOST_PORT:$CONTAINER_PORT\"" >> docker-compose.yml

          echo "Docker Compose File Content:"

          cat docker-compose.yml
      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose
          path: docker-compose.yml
